Repository paketo-buildpacks/occam, pull requests merged in 2025-03, with the labels that each got.

#356 feat: filematchers follow symlinks
  matchers/have_file.go
  matchers/have_file_test.go
  matchers/have_file_with_content.go
  matchers/have_file_with_content_test.go
Labels: enhancement, semver:minor

#363 Dependency downgrade
  fakes/daemon_client.go
  go.mod
  go.sum
Labels: semver:minor

#373 Adding support for packaging multi-arch extension based on the OS architecture
  packagers/jam.go
  packagers/jam_test.go
Labels: enhancement, semver:patch
